name: Message Echo 2

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to echo'
        required: false
        default: 'this is echo 2'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message with a wait
        run: |
          sleep 11
          echo '${{ inputs.message }}'
